### ISSUE TITLE
Primary colour option

### ISSUE THREAD

**Issue by ryanfurtner** [elementor/hello-theme#97] opened 2019-10-04 00:45 UTC
Shouldnt there be a simple option to change the primary theme colour from '#c36'?

**Comment by mbaierl** [comment] 2019-10-10 09:00
The same applies to links - there is no easy way of overriding the default color option...

**Comment by homesinfra** [comment] 2019-10-16 05:47
Yes, the pink color on links cant be overridden on elementor. So had to use yellow pencil.

**Comment by nuritsha** [comment] 2019-10-22 07:51
Hi @ryanfurtner, @mbaierl & @homesinfra,

We are working on a solution for global settings (which will be part of the plugin, not the theme), but it is not ready just yet. 
In the mean time, please use good-old css.

Thanks!

**Comment by nuritsha** [comment] 2019-10-22 07:51
Duplicate of #57

**Closed by nuritsha** 2019-10-22 07:51 UTC

**Comment by nadworks** [comment] 2021-02-18 20:03
Sorry, is there an update? Using HELLO a lot, but the lack of global colour over-write is still missing and it's been over a year since this thread was "closed".
