### ISSUE TITLE
Changing links color

### ISSUE THREAD

**Issue by Th3BiSh0p** [elementor/hello-theme#103] opened 2019-12-02 12:55 UTC
Hello, I'm using Hello for several websites. It's simple and it's great but it is lacking at least one customisation imo : the ability to change the links color.
It seems I can't change it globally in elementor, it's usually a setting in the theme, but in Hello it doesn't exist.

It is still possible to change it with custom css but it would be great to have a way to set it, either in Hello or in elementor.

Thanks

**Comment by nuritsha** [comment] 2019-12-02 14:05
Duplicate of #57 and #97

**Closed by nuritsha** 2019-12-02 14:05 UTC
